### ISSUE TITLE
Current TODO items

### ISSUE THREAD

**Issue by oowekyala** [tud-ccc/Cinnamon#2]
## High priority

- [x] #4
- [x] Linkage issue with memrefCopy
- [x] Checking that VA runs (@h4midf)
- [ ] Add histogram op (@h4midf)
    - In CINM
    - In CINM->CNM
- [ ] #7
- [ ] #6
- [x] Write a README
- [ ] Remove artifact-specific stuff

## Cost model (deadline 04.08)

Currently we have `cinm.compute` with attributes for workgroup shape and DPU memory size.
We assume this specification is correct, that is, the lowering pass cannot change them.
They should be obtained through the cost model.

- [ ] Implement a simple Samsung dialect
- [ ] Implement a pass that annotates Samsung and Upmem kernels with their time estimation 
	- [ ] Implement the upmem cost estimator in C++

## Lower priority

- [x] Add verifier for shape of scatter map in UPMEM
- [ ] Fix the GPU lowering, was probably broken by recent changes to CNM

### Optimization

- [x] Hoist buffer alloc and free outside of loops
- [ ] Malloc avoidance
   - [x] Avoid tensor reshapes that do a copy (Especially for VA that's a problem)
   - [x] Unify buffers across loop iterations
- [x] Affine map simplification with dimension sizes
